USE [master]
GO
/****** Object:  Database [PolishData]    Script Date: 17-Apr-17 10:32:45 PM ******/
CREATE DATABASE [PolishData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PolishData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\PolishData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PolishData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\PolishData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [PolishData] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PolishData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PolishData] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PolishData] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PolishData] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PolishData] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PolishData] SET ARITHABORT OFF 
GO
ALTER DATABASE [PolishData] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PolishData] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PolishData] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PolishData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PolishData] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PolishData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PolishData] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PolishData] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PolishData] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PolishData] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PolishData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PolishData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PolishData] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PolishData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PolishData] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PolishData] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PolishData] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PolishData] SET RECOVERY FULL 
GO
ALTER DATABASE [PolishData] SET  MULTI_USER 
GO
ALTER DATABASE [PolishData] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PolishData] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PolishData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PolishData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PolishData] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'PolishData', N'ON'
GO
ALTER DATABASE [PolishData] SET QUERY_STORE = OFF
GO
USE [PolishData]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [PolishData]
GO
/****** Object:  Table [dbo].[FacebookRecord]    Script Date: 17-Apr-17 10:32:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FacebookRecord](
	[Date] [nvarchar](100) NULL,
	[Firstnames] [nvarchar](100) NULL,
	[Surname] [nvarchar](100) NULL,
	[PoliceDistrict] [nvarchar](1000) NULL,
	[Reason] [nvarchar](max) NULL,
	[Age] [nvarchar](100) NULL,
	[Description] [nvarchar](max) NULL,
	[NameofImagelink] [nvarchar](max) NULL,
	[Facebooklink] [nvarchar](max) NULL,
	[Comment] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PolishEvent]    Script Date: 17-Apr-17 10:32:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PolishEvent](
	[FileDate] [date] NOT NULL,
	[Title] [nvarchar](max) NULL,
	[Episode] [numeric](5, 0) NULL,
	[Date] [nvarchar](50) NULL,
	[Description] [nvarchar](max) NULL,
	[Image] [nvarchar](500) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PolishRecord]    Script Date: 17-Apr-17 10:32:45 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PolishRecord](
	[Date] [date] NULL,
	[FirstName] [nvarchar](500) NULL,
	[TextField] [nvarchar](max) NULL,
	[Area] [nvarchar](1000) NULL,
	[LikelyArea] [nvarchar](1000) NULL,
	[Age] [numeric](3, 0) NULL,
	[Description] [nvarchar](max) NULL,
	[Link_To_Photo] [nvarchar](500) NULL,
	[MiddleName] [nvarchar](500) NULL,
	[LastName] [nvarchar](500) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [PolishData] SET  READ_WRITE 
GO
